# ICSE Class 9 Flashcards dataset

# Format: (chapter_number, chapter_title, front, back, explanation)
icse9_cards = [
    # Chapter 1: Introduction to OOP
    (1, "Ch 1: Introduction to OOP", 
     "What is Object-Oriented Programming (OOP)?", 
     "A programming paradigm based on the concept of 'objects' containing data and code.", 
     "OOP models real-world entities using objects. It revolves around four core principles: Encapsulation, Abstraction, Inheritance, and Polymorphism."),
    
    (1, "Ch 1: Introduction to OOP", 
     "What is a Class?", 
     "A blueprint or template that defines the structure and behavior of objects.", 
     "A class is a logical entity (user-defined data type) from which individual objects are created. It contains variables and methods."),

    (1, "Ch 1: Introduction to OOP", 
     "What is an Object?", 
     "An instance of a class that represents a real-world entity with state and behavior.", 
     "Objects have states (represented by variables) and behaviors (represented by methods). They occupy physical memory space when created."),

    (1, "Ch 1: Introduction to OOP", 
     "Differentiate between Class and Object.", 
     "Class is the blueprint (logical); Object is the instance (physical).", 
     "A class does not occupy memory space until an object is instantiated using the 'new' keyword. Class is a data type, Object is a variable of that type."),

    (1, "Ch 1: Introduction to OOP", 
     "What is Encapsulation?", 
     "Wrapping of data (variables) and methods into a single unit (class).", 
     "Encapsulation binds data and code together. It keeps them safe from external interference and misuse, often implemented using private variables and public getters/setters."),

    (1, "Ch 1: Introduction to OOP", 
     "What is Data Abstraction?", 
     "Act of representing essential features without including background details.", 
     "Abstraction focuses on what an object does rather than how it does it. In Java, it is achieved using abstract classes and interfaces."),

    (1, "Ch 1: Introduction to OOP", 
     "What is Inheritance?", 
     "Mechanism where one class acquires the properties and behaviors of another class.", 
     "Inheritance supports code reusability. The class that inherits is the subclass (child), and the class inherited from is the superclass (parent). Uses the 'extends' keyword."),

    (1, "Ch 1: Introduction to OOP", 
     "What is Polymorphism?", 
     "The ability of a message or function to be processed in more than one form.", 
     "Polymorphism means 'many forms'. It is implemented in Java via method overloading (compile-time) and method overriding (run-time)."),

    (1, "Ch 1: Introduction to OOP", 
     "What is Data Hiding?", 
     "Restricting direct access to class members from outside the class.", 
     "Data hiding is achieved using private access modifiers. It is a subset of encapsulation that protects sensitive data from direct modifications."),

    (1, "Ch 1: Introduction to OOP", 
     "Differentiate: Procedure-Oriented (POP) vs Object-Oriented (OOP)", 
     "POP focuses on functions/procedures; OOP focuses on data security and objects.", 
     "In POP, data moves freely around the system and is vulnerable. In OOP, data is tied closely to methods, preventing unauthorized access."),

    (1, "Ch 1: Introduction to OOP", 
     "Why is Java called an Object-Oriented Language?", 
     "Because almost everything in Java is modeled around classes and objects.", 
     "Java enforces the OOP paradigm. Except for primitive data types, all data and actions must reside within a class hierarchy."),

    # Chapter 2: Introduction to Java
    (2, "Ch 2: Introduction to Java", 
     "What is JVM?", 
     "Java Virtual Machine - an interpreter that executes compiled bytecode.", 
     "JVM acts as a virtual machine that runs compiled Java class files (.class). It is platform-dependent and translates bytecode into machine code for the host OS."),

    (2, "Ch 2: Introduction to Java", 
     "What is JDK?", 
     "Java Development Kit - software kit containing tools to write and run Java.", 
     "JDK contains the compiler (javac), runtime environment (JRE), launcher (java), and other developer tools needed to build Java programs."),

    (2, "Ch 2: Introduction to Java", 
     "What is Bytecode?", 
     "An intermediate, machine-independent instruction set generated by javac.", 
     "Bytecode is saved in '.class' files. It is not readable by CPUs directly; instead, JVM interprets or JIT-compiles it at runtime."),

    (2, "Ch 2: Introduction to Java", 
     "Differentiate: Source Code vs Bytecode", 
     "Source Code is written in high-level language (.java); Bytecode is compiled intermediate code (.class).", 
     "Source code is human-readable and platform-independent. Bytecode is generated by compiler for JVM execution."),

    (2, "Ch 2: Introduction to Java", 
     "What is platform independence in Java?", 
     "The ability to run Java program bytecode on any operating system without changes.", 
     "Java compiled bytecode (.class) runs on any machine that has a compatible JVM installed. This is known as 'Write Once, Run Anywhere' (WORA)."),

    (2, "Ch 2: Introduction to Java", 
     "What is the purpose of main() method?", 
     "It is the entry point where JVM starts executing the Java program.", 
     "The exact signature 'public static void main(String[] args)' is required so JVM can locate and launch the program's main thread."),

    (2, "Ch 2: Introduction to Java", 
     "What is JIT Compiler?", 
     "Just-In-Time Compiler - compiles hot bytecode sections into native machine code at runtime.", 
     "JIT works inside the JVM. Instead of interpreting bytecode line-by-line repeatedly, it compiles frequently executed sections directly to machine code for speed."),

    (2, "Ch 2: Introduction to Java", 
     "Differentiate: Compiler vs Interpreter", 
     "Compiler translates whole program at once; Interpreter translates line-by-line.", 
     "The Java compiler (javac) translates source code (.java) into bytecode (.class). The JVM interpreter translates bytecode into machine code during execution."),

    # Chapter 3: Values & Data Types
    (3, "Ch 3: Values & Data Types", 
     "Differentiate: Primitive vs Non-Primitive Types", 
     "Primitive types are predefined basic types; Non-primitive types are user-defined references.", 
     "Primitive data types (int, double, char, etc.) store raw values directly. Non-primitive data types (Strings, Arrays, Classes) store reference addresses of memory blocks."),

    (3, "Ch 3: Values & Data Types", 
     "What are the sizes of int and long in Java?", 
     "int is 4 bytes (32-bit); long is 8 bytes (64-bit).", 
     "Both are signed integer types. A long literal is denoted with an 'L' suffix (e.g. 5000000000L)."),

    (3, "Ch 3: Values & Data Types", 
     "Differentiate: float vs double", 
     "float is 4 bytes (single-precision); double is 8 bytes (double-precision).", 
     "In Java, default decimal literals are double (e.g., 3.14). To define a float, append 'f' or 'F' (e.g., 3.14f)."),

    (3, "Ch 3: Values & Data Types", 
     "Differentiate: char vs String", 
     "char stores a single character in single quotes; String stores multiple characters in double quotes.", 
     "char is a primitive type (2 bytes, Unicode). String is a class/non-primitive reference type."),

    (3, "Ch 3: Values & Data Types", 
     "What character encoding does Java use?", 
     "Unicode character set (UTF-16, 2 bytes per char).", 
     "Unlike older languages using 1-byte ASCII, Java uses Unicode to support global scripts and characters, ranging from 0 to 65,535."),

    (3, "Ch 3: Values & Data Types", 
     "What is Implicit Type Conversion (Widening)?", 
     "Automatic conversion of a smaller data type to a larger data type by the compiler.", 
     "Also known as promotion. No loss of data. Order: byte -> short -> char -> int -> long -> float -> double."),

    (3, "Ch 3: Values & Data Types", 
     "What is Explicit Type Conversion (Casting)?", 
     "Manual conversion of a larger data type to a smaller data type, written in parentheses.", 
     "Also known as narrowing. Can lead to loss of precision/overflow. E.g., int x = (int) 5.9; resulting in 5."),

    (3, "Ch 3: Values & Data Types", 
     "What is an Escape Sequence?", 
     "Special characters prefixed with a backslash to format text or output.", 
     "E.g., '\\n' for newline, '\\t' for horizontal tab, '\\\\' for backslash, and '\\\"' for double quotes."),

    (3, "Ch 3: Values & Data Types", 
     "Differentiate: Identifiers vs Keywords", 
     "Identifiers are user-defined names; Keywords are reserved names with special meanings.", 
     "Keywords (class, public, int, if) cannot be used as identifiers (variable names, method names). Identifiers must follow naming rules."),

    (3, "Ch 3: Values & Data Types", 
     "What is a Constant in Java?", 
     "A variable whose value cannot be modified once initialized, declared using 'final'.", 
     "E.g., final double PI = 3.14159; Any attempt to reassign a final variable triggers a compilation error."),

    # Chapter 4: Operators
    (4, "Ch 4: Operators", 
     "Differentiate: Pre-increment (++i) vs Post-increment (i++)", 
     "++i increments first then uses value; i++ uses value first then increments.", 
     "If i = 5: ++i increments to 6 and returns 6. i++ returns 5, then increments i to 6 in memory."),

    (4, "Ch 4: Operators", 
     "Differentiate: Logical AND (&&) vs Bitwise AND (&) in condition", 
     "&& is short-circuit (skips evaluation if LHS is false); & evaluates both operands.", 
     "Short-circuit && is efficient. If LHS evaluates to false, && immediately returns false without evaluating the RHS (preventing runtime crashes)."),

    (4, "Ch 4: Operators", 
     "Differentiate: = vs ==", 
     "= is the assignment operator; == is the comparison/relational operator.", 
     "Use = to store a value in a variable (e.g., x = 5). Use == to check if two primitives are equal (e.g., if (x == 5))."),

    (4, "Ch 4: Operators", 
     "What is the Ternary Operator?", 
     "A shorthand for if-else that assigns a value based on a condition: condition ? expr1 : expr2.", 
     "Also called conditional operator. E.g., max = (a > b) ? a : b;"),

    (4, "Ch 4: Operators", 
     "What are binary and unary operators?", 
     "Unary operators act on 1 operand; Binary operators act on 2 operands.", 
     "Unary examples: ++, --, -, !. Binary examples: +, -, *, /, %."),

    # Chapter 5: Input in Java
    (5, "Ch 5: Input in Java", 
     "What class is commonly used for terminal input in Java?", 
     "java.util.Scanner class.", 
     "It reads user inputs from standard input stream (System.in). Created using: Scanner sc = new Scanner(System.in);"),

    (5, "Ch 5: Input in Java", 
     "Differentiate: sc.next() vs sc.nextLine()", 
     "next() reads a single token (word); nextLine() reads a complete line of text.", 
     "sc.next() stops at white space or space. sc.nextLine() reads characters until it hits a newline ('\\n')."),

    (5, "Ch 5: Input in Java", 
     "Why must Scanner be imported?", 
     "Because it belongs to the java.util package, not the default java.lang package.", 
     "Java automatically imports java.lang.*. For other classes, you must use import statements, e.g., import java.util.Scanner;"),

    # Chapter 6: Mathematical Library Methods
    (6, "Ch 6: Math Library", 
     "Differentiate: Math.ceil(x) vs Math.floor(x)", 
     "ceil(x) rounds up (towards positive infinity); floor(x) rounds down.", 
     "Both return double values. E.g., Math.ceil(-4.8) is -4.0. Math.floor(-4.8) is -5.0."),

    (6, "Ch 6: Math Library", 
     "What is the return type of Math.sqrt()?", 
     "double.", 
     "Math.sqrt() always returns a double value representing the square root of the argument. E.g. Math.sqrt(9) yields 3.0."),

    (6, "Ch 6: Math Library", 
     "Differentiate: Math.round(x) for float vs double", 
     "round(float) returns int; round(double) returns long.", 
     "Math.round() rounds to the nearest integer. Add 0.5 and truncate. E.g., Math.round(2.5) is 3."),

    (6, "Ch 6: Math Library", 
     "What is the range of values returned by Math.random()?", 
     "Greater than or equal to 0.0 and strictly less than 1.0 ( [0.0, 1.0) ).", 
     "It returns a pseudorandom double. To get integer ranges, multiply and cast: e.g. (int)(Math.random() * 10) returns 0 to 9."),

    # Chapter 7: Conditional Constructs
    (7, "Ch 7: Conditional Constructs", 
     "What is a Switch-Case Statement?", 
     "A multi-way branching statement that tests a variable against multiple constant values.", 
     "Matches expressions of types: byte, short, char, int, String, or enums. Compares strictly for equality."),

    (7, "Ch 7: Conditional Constructs", 
     "What is Switch Case Fall-Through?", 
     "When code executions cascade through case labels because a break statement was omitted.", 
     "If a break is missing, Java continues executing instructions in subsequent cases regardless of whether they match the switch expression."),

    (7, "Ch 7: Conditional Constructs", 
     "What is the purpose of 'default' in switch-case?", 
     "It executes when none of the case constants match the switch expression.", 
     "It acts like the final 'else' in an if-else ladder. It is optional but recommended. Doesn't need a break if it is the last line."),

    # Chapter 8: Iterative Constructs
    (8, "Ch 8: Iterative Constructs", 
     "Differentiate: Entry-controlled vs Exit-controlled loops", 
     "Entry-controlled checks condition before executing loop body; Exit-controlled checks after.", 
     "while and for are entry-controlled (might run 0 times). do-while is exit-controlled (always executes body at least once)."),

    (8, "Ch 8: Iterative Constructs", 
     "What is an Infinite Loop?", 
     "A loop whose termination condition is never satisfied, running indefinitely.", 
     "E.g., while(true) { ... } or for(;;) { ... } where update conditions never make the loop test condition evaluate to false."),

    (8, "Ch 8: Iterative Constructs", 
     "Differentiate: break vs continue", 
     "break terminates and exits the loop; continue skips the rest of the current iteration and jumps to the next loop pass.", 
     "break jumps out of loop bounds. continue skips subsequent lines in the loop body and jumps directly to update/condition headers."),

    (8, "Ch 8: Iterative Constructs", 
     "What is a Null Loop (or Empty Loop)?", 
     "A loop containing no executable statements in its body.", 
     "E.g., for(int i=0; i<10; i++); (note the terminating semicolon). It is used to generate time delays, but is often a syntax mistake."),

    # Chapter 9: Nested Loops
    (9, "Ch 9: Nested Loops", 
     "What is a Nested Loop?", 
     "A loop inside another loop body.", 
     "For each iteration of the outer loop, the inner loop executes its complete cycle. Frequently used to traverse grids or print patterns."),

    (9, "Ch 9: Nested Loops", 
     "What is a Labeled Break?", 
     "A break statement that specifies a block label to exit out of outer nested structures.", 
     "E.g., outer: for(...) { for(...) { break outer; } } terminates both loops immediately, rather than just the inner loop.")
]
